# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-25 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='potato',
            name='colors',
            field=models.CharField(default='white and black', max_length=200),
        ),
        migrations.AddField(
            model_name='potato',
            name='description',
            field=models.CharField(default='Not Reddit', max_length=1000),
        ),
        migrations.AddField(
            model_name='potato',
            name='image_url',
            field=models.CharField(default='9gag.com', max_length=200),
        ),
        migrations.AlterField(
            model_name='potato',
            name='name',
            field=models.CharField(default='9gag', max_length=50),
        ),
        migrations.AlterField(
            model_name='potato',
            name='species',
            field=models.CharField(default='netizen', max_length=50),
        ),
        migrations.AlterField(
            model_name='potato',
            name='variety',
            field=models.CharField(default='normie', max_length=50),
        ),
    ]
